### ISSUE TITLE
easy handye result not matching with tf publish

### ISSUE THREAD

**Issue by Akumar201** [IFL-CAMP/easy_handeye#119]
HI, I did a eye on base calibration, however I am not sure why the two results are coming different 

this is my yaml file 

```
parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: xarm6
  move_group_namespace: /
  namespace: /my_eob_calib_eye_on_base/
  robot_base_frame: link_base
  robot_effector_frame: link_eef
  tracking_base_frame: camera_color_optical_frame
  tracking_marker_frame: camera_marker
transformation:
  qw: 0.04552599706372636
  qx: -0.01619861515451026
  qy: -0.7122531129990347
  qz: 0.7002574465734831
  x: 0.2417231964218327
  y: 1.9499142173233568
  z: 1.0518465171162283

```
and this is `rosrun tf tf_echo camera_color_optical_frame link_base`
```
At time 0.000
- Translation: [0.027, 1.024, 1.979]
- Rotation: in Quaternion [0.016, 0.712, -0.700, 0.046]
            in RPY (radian) [-1.586, 0.088, -3.101]
            in RPY (degree) [-90.870, 5.022, -177.659]

```
