### ISSUE TITLE
Transformation seems to be wrong for eye-in-hand

### ISSUE THREAD

**Issue by ForsenCD** [IFL-CAMP/easy_handeye#23]
Hi,

first of all thank you for this tool. It was easy to setup and it looks to be promising for my project.

I used the gui to get the **eye-in-hand** transformation for my Asus Xtion and the UR5. The camera is mounted on the end-effector. I am trying to transform camera coordinates from a tracked object to the end effector frame of my UR5 and the move the robot to those coordinates. But somehow the transformation does not give me the expected results. Here's my data:

### Transformation.yaml
```

eye_on_hand: true
robot_effector_frame: ee_link
tracking_base_frame: primesense_link
transformation: {qw: 0.12315000298790331, qx: -0.989347167929719, qy: -0.07459459276842946,
qz: 0.02149197066897385, x: 0.04013691589594168, y: -0.13677498325817272, z: 0.08220400023605642}
```

### Grasp_Camera_data
```
   position: 
       x: -0.0987664492927
       y: -0.0910226523694
       z: 0.560733250459
   orientation: 
       x: 0.631932686942
       y: 0.31727130216
       z: 0.631932686942
       w: -0.31727130216
  q_value: 0.678789377213
  grasp_type: 0
  center_px: [226.52753499783466, 153.77785122466588]
  angle: -0.640199793927
  depth: 0.560733250459
  ...
```

### Camera_ee_transform:
```
header: 
seq: 0
frame_id: "primesense_link"
child_frame_id: "ee_link"
transform: 
translation: 
    x: 0.040137
    y: -0.136775
    z: 0.082204
rotation: 
    x: -0.989347006868672
    y: -0.0745944036699313
    z: 0.021491953634446583
    w: 0.12315016789268264
```
Then I used t2f to calcualte the grasp in the ee pose
`
grasp_ee_pose = tf2_geometry_msgs.do_transform_pose(grasp_camera_pose, camera_ee_transform)`

The result is incorrect. Here are the actual results and my expected results for the translation:
```
grasp_ee_pose_translation_actual:
x = -0.104539997152
y  = 0.0702126802005
z = -0.436145472381
```
```

grasp_ee_pose_translation_expected:

x =  0.362407802611
y =  0.667193262606
z =  0.050243921518
```
What am I missing? Thank you!
